set -g prefix C-a
bind C-a send-prefix
unbind C-b

set -g default-terminal screen-256color
set -g status-keys vi
set -g history-limit 9999999

set -g mouse on
unbind -n MouseDrag1Pane
setw -g mode-keys vi
setw -g monitor-activity on

bind-key v split-window -h
bind-key s split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Use arrow keys prefix key to switch panes
bind Left previous-window
bind Right next-window

# Turn off confirmation while closing a pane
unbind x
bind x kill-pane

# No delay for escape key press
set -sg escape-time 0

# Reload tmux config
bind r source-file ~/.tmux.conf

# Plugins
set -g @plugin 'tmux-plugins/tpm'

# Catpuccin
set -g @plugin 'catppuccin/tmux#v2.1.0'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_date_time_text '%d.%m. %H:%M'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -agF status-right "#{E:@catppuccin_status_session}"
set-window-option -g status-position top

# Dracula
# set -g @plugin 'dracula/tmux'
# set -g @dracula-plugins "cpu-usage gpu-usage ram-usage"
# set -g @dracula-cpu-usage-label "CPU"
# set -g @dracula-cpu-display-load true
# set -g @dracula-battery-label "Battery"
# set -g @dracula-gpu-usage-label "GPU"
# set -g @dracula-ram-usage-label "RAM"
# set -g @dracula-tmux-ram-usage-label "MEM"
# set -g @dracula-network-bandwidth eth0
# set -g @dracula-network-bandwidth-interval 0
# set -g @dracula-network-bandwidth-show-interface true
#
# set -g @dracula-cpu-usage-colors "pink dark_gray"
# set -g @dracula-show-powerline true
# set -g @dracula-plugins "weather"
# set -g @dracula-show-location true
# set -g @dracula-fixed-location "Pune"
# set -g @dracula-show-fahrenheit false
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon session
# set -g status-position top

# Tmux copy to clipboard
set -g @plugin 'tmux-plugins/tmux-yank'

# Tmux logging
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @logging-path '#{pane_current_path}'
set -g @save-complete-history-path '#{pane_current_path}'
set -g @screen-capture-path '#{pane_current_path}'

run '~/.tmux/plugins/tpm/tpm'
