# Makes hyprsunset do nothing to the screen by default
# Without this, the default applies some tint to the monitor
profile {
    time = 00:00
    temperature = 5000 # set in /home/soham/dotfiles/binomarchy/omarchy-toggle-nightlight
    # gamma = 0.8   
    identity = false
}
