# apply all images from the wallpapers directory to every monitor
wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpapers/
    fit_mode = cover    # contain, cover, tile, fit
    # timeout = 1800          # seconds to rotate images (0 = static)
}

ipc = true
splash = false
