[mgr]
linemode = "size"

[opener]
edit = [
  { run = 'nvim %*', block = true, for = "windows", desc = "Edit in Neovim" },
  { run = 'nvim "$0"', block = true, for = "unix", desc = "Edit in Neovim" },
]
open = [
  { run = "pwsh.exe -NoProfile -NoLogo -Command \"Invoke-Item -LiteralPath '%0'\"", for = "windows", desc = "Open by default app" },
  { run = 'xdg-open "$0"', for = "unix", desc = "Open with default app" },
]

[open]
# Replace defaults fully to ensure our rules apply
rules = [
  { mime = "text/*", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.lua", use = "edit" },
  # Fallback
  { name = "*", use = "open" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
