[mgr]
linemode = "size"
show_hidden = true

[preview]
max_height = 700

[opener]
edit = [
  { run = 'nvim %*', block = true, for = "windows", desc = "Edit in Neovim" },
  { run = 'nvim "$@"', block = true, for = "unix", desc = "Edit in Neovim" },
]
play = [
  { run = 'cine "$@"', orphan = true, block = false, for = "unix", desc = "Play media in Cine" },
  { run = 'vlc "$@"', orphan = true, block = false, for = "unix", desc = "Play media in VLC" },
]
# Added Loupe opener here
view_image = [
  { run = 'loupe "$@"', orphan = true, for = "unix", desc = "View in Loupe" },
]
open = [
  { run = "pwsh.exe -NoProfile -NoLogo -Command \"Invoke-Item -LiteralPath '%0'\"", for = "windows", desc = "Open by default app" },
  { run = 'xdg-open "$@"', for = "unix", desc = "Open with default app" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { url = "*.toml", use = "edit" },
  { url = "*.lua", use = "edit" },
  # Added image rule here
  { mime = "image/*", use = "view_image", for = "unix" },
  { mime = "video/*", use = "play", for = "unix" },
  # Fallback
  { url = "*", use = "open" },
]

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
group = "git"
